spring:
  datasource:
    url: jdbc:mysql://localhost:3306/m_actores
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

info:
  name: ActorService
  description: Servicio de los Actores
  version: 0.0.1-SNAPSHOT
