spring:
  datasource:
    url: jdbc:mysql://localhost:3306/m_episodios
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

info:
  name: EpisodioService
  description: Servicio de los episodios
  version: 0.0.1-SNAPSHOT
